성server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mileage?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: mileage-user
      password: mileage-pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    user: mileage-user
    password: mileage-pass
    schemas: mileage
    url: jdbc:mysql://localhost:3306/mileage?serverTimezone=UTC&characterEncoding=UTF-8
    enabled: true

logging:
  level:
    root:
      info
    org:
      hibernate:
        SQL: debug